apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Github-Trending-Repo-App
  annotations:
    github.com/project-slug: DipeshSingh1772/Github-Trending-Repo-App
spec:
  type: other
  lifecycle: unknown
  owner: guests
